### ISSUE TITLE
What is the homework for tutorial lession week 2?

### ISSUE THREAD

**Issue by viethoanggithub** [congnv8192/2015_ppl_5c13_group2#1]
@congnv8192 
Dear teacher, is there any homework that we should do in advance for our lession in week 3? Do we need to do and commit the homework to this repo?

**Comment by congnv8192** [comment]
Yes, please read the tutorial note which refer to the exercises listed in the course module description 
Exercises for all weeks - check http://fit.hanu.edu.vn/fitportal/file.php/216/FIT325_moddesc.pdf

All these exercises are from the text book 
http://math.hws.edu/javanotes/
Cheers,
